import type { WarpPreset } from '@app-types/preset';

export const defaultWarpPreset: WarpPreset = {
  version: 1,
  appearance: {
    skinSmoothing: {
      type: 'skin_smoothing',
      enabled: true,
      strength: 0.35,
      radius: 1.0,
      maskOpacity: 1,
      showMaskPreview: false,
    },
    skinTone: {
      type: 'skin_tone',
      enabled: true,
      brightness: 0.03,
      saturation: 1.05,
      warmth: 0.05,
      blend: 0.6,
    },
  },
  operations: [
    {
      id: 'left_eye_enlarge',
      enabled: true,
      type: 'radial_warp',
      target: 'left_eye',
      strength: 0.08,
      radius: 1.8,
      falloff: {
        type: 'smoothstep',
      },
      axis: {
        x: 1,
        y: 0.7,
      },
      direction: {
        x: 0,
        y: 0,
      },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.12,
      polygon: [{ x: 0.3, y: 0.35 }, { x: 0.5, y: 0.25 }, { x: 0.7, y: 0.35 }, { x: 0.65, y: 0.55 }, { x: 0.35, y: 0.55 }],
    },
    {
      id: 'right_eye_enlarge',
      enabled: true,
      type: 'radial_warp',
      target: 'right_eye',
      strength: 0.08,
      radius: 1.8,
      falloff: {
        type: 'smoothstep',
      },
      axis: {
        x: 1,
        y: 0.7,
      },
      direction: {
        x: 0,
        y: 0,
      },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.12,
      polygon: [{ x: 0.3, y: 0.35 }, { x: 0.5, y: 0.25 }, { x: 0.7, y: 0.35 }, { x: 0.65, y: 0.55 }, { x: 0.35, y: 0.55 }],
    },
    {
      id: 'left_face_slim',
      enabled: true,
      type: 'line_warp',
      target: 'left_jaw',
      strength: 0.05,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: 0.03, y: 0 },
      lineStart: { x: 0.25, y: 0.45 },
      lineEnd: { x: 0.45, y: 0.72 },
      width: 0.09,
      polygon: [{ x: 0.22, y: 0.42 }, { x: 0.42, y: 0.42 }, { x: 0.45, y: 0.7 }, { x: 0.28, y: 0.76 }],
      binding: {
        type: 'landmark_line',
        start: 'left_cheek',
        end: 'chin',
      },
    },
    {
      id: 'right_face_slim',
      enabled: true,
      type: 'line_warp',
      target: 'right_jaw',
      strength: 0.05,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: -0.03, y: 0 },
      lineStart: { x: 0.75, y: 0.45 },
      lineEnd: { x: 0.55, y: 0.72 },
      width: 0.09,
      polygon: [{ x: 0.58, y: 0.42 }, { x: 0.78, y: 0.42 }, { x: 0.72, y: 0.76 }, { x: 0.55, y: 0.7 }],
      binding: {
        type: 'landmark_line',
        start: 'right_cheek',
        end: 'chin',
      },
    },
    {
      id: 'left_cheek_lift',
      enabled: true,
      type: 'region_warp',
      target: 'left_cheek',
      strength: -0.035,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: 0, y: -0.8 },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.06,
      polygon: [{ x: 0.25, y: 0.45 }, { x: 0.35, y: 0.42 }, { x: 0.4, y: 0.58 }, { x: 0.27, y: 0.63 }],
      binding: { type: 'landmark_region', region: 'left_cheek' },
      weightMap: { type: 'radial_gradient', center: { x: 0.33, y: 0.52 }, radius: 0.16 },
    },
    {
      id: 'right_cheek_lift',
      enabled: true,
      type: 'region_warp',
      target: 'right_cheek',
      strength: -0.035,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: 0, y: -0.8 },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.06,
      polygon: [{ x: 0.6, y: 0.42 }, { x: 0.73, y: 0.45 }, { x: 0.71, y: 0.63 }, { x: 0.58, y: 0.58 }],
      binding: { type: 'landmark_region', region: 'right_cheek' },
      weightMap: { type: 'radial_gradient', center: { x: 0.67, y: 0.52 }, radius: 0.16 },
    },
  ],
};
