import type { WarpPreset } from '@app-types/preset';
import { CURRENT_PRESET_SCHEMA_VERSION } from '@engine/presets/presetSchema';

export const liteBeautyPreset: WarpPreset = {
  schemaVersion: CURRENT_PRESET_SCHEMA_VERSION,
  id: 'lite_beauty',
  name: '軽量美顔',
  description: 'モバイル・長時間配信向けの低負荷プリセット',
  appearance: {
    skinSmoothing: {
      type: 'skin_smoothing',
      enabled: true,
      strength: 0.18,
      radius: 0.9,
      maskOpacity: 0.78,
      showMaskPreview: false,
    },
    skinTone: {
      type: 'skin_tone',
      enabled: true,
      brightness: 0.01,
      saturation: 1.02,
      warmth: 0.01,
      blend: 0.22,
    },
  },
  operations: [
    {
      id: 'left_eye_lite_enlarge',
      enabled: true,
      type: 'radial_warp',
      target: 'left_eye',
      strength: 0.04,
      radius: 1.68,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 0.84 },
      direction: { x: 0, y: 0 },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.12,
      polygon: [],
      weightMap: { type: 'radial_gradient', center: { x: 0.5, y: 0.5 }, radius: 0.78 },
    },
    {
      id: 'right_eye_lite_enlarge',
      enabled: true,
      type: 'radial_warp',
      target: 'right_eye',
      strength: 0.04,
      radius: 1.68,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 0.84 },
      direction: { x: 0, y: 0 },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.12,
      polygon: [],
      weightMap: { type: 'radial_gradient', center: { x: 0.5, y: 0.5 }, radius: 0.78 },
    },
    {
      id: 'left_jaw_lite_slim',
      enabled: true,
      type: 'line_warp',
      target: 'left_jaw',
      strength: 0.03,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: 0.015, y: 0 },
      lineStart: { x: 0.25, y: 0.47 },
      lineEnd: { x: 0.46, y: 0.73 },
      width: 0.1,
      polygon: [],
      binding: { type: 'landmark_line', start: 'left_cheek', end: 'chin' },
    },
    {
      id: 'right_jaw_lite_slim',
      enabled: true,
      type: 'line_warp',
      target: 'right_jaw',
      strength: 0.03,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: -0.015, y: 0 },
      lineStart: { x: 0.75, y: 0.47 },
      lineEnd: { x: 0.54, y: 0.73 },
      width: 0.1,
      polygon: [],
      binding: { type: 'landmark_line', start: 'right_cheek', end: 'chin' },
    },
  ],
};
