import type { WarpPreset } from '@app-types/preset';
import { CURRENT_PRESET_SCHEMA_VERSION } from '@engine/presets/presetSchema';

export const naturalPreset: WarpPreset = {
  schemaVersion: CURRENT_PRESET_SCHEMA_VERSION,
  id: 'natural_beauty',
  name: 'ナチュラル美顔',
  description: '加工感を抑えた、配信用の標準プリセット',
  appearance: {
    skinSmoothing: {
      type: 'skin_smoothing',
      enabled: true,
      strength: 0.22,
      radius: 0.96,
      maskOpacity: 0.8,
      showMaskPreview: false,
    },
    skinTone: {
      type: 'skin_tone',
      enabled: true,
      brightness: 0.01,
      saturation: 1.02,
      warmth: 0.02,
      blend: 0.28,
    },
  },
  operations: [
    {
      id: 'left_eye_natural_enlarge',
      enabled: true,
      type: 'radial_warp',
      target: 'left_eye',
      strength: 0.04,
      radius: 1.75,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 0.82 },
      direction: { x: 0, y: 0 },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.12,
      polygon: [],
      weightMap: { type: 'radial_gradient', center: { x: 0.5, y: 0.5 }, radius: 0.82 },
    },
    {
      id: 'right_eye_natural_enlarge',
      enabled: true,
      type: 'radial_warp',
      target: 'right_eye',
      strength: 0.04,
      radius: 1.75,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 0.82 },
      direction: { x: 0, y: 0 },
      lineStart: { x: 0.3, y: 0.5 },
      lineEnd: { x: 0.7, y: 0.5 },
      width: 0.12,
      polygon: [],
      weightMap: { type: 'radial_gradient', center: { x: 0.5, y: 0.5 }, radius: 0.82 },
    },
    {
      id: 'nose_refine',
      enabled: true,
      type: 'radial_warp',
      target: 'nose',
      strength: -0.025,
      radius: 1.2,
      falloff: { type: 'smoothstep' },
      axis: { x: 0.82, y: 1 },
      direction: { x: 0, y: 0 },
      lineStart: { x: 0.45, y: 0.35 },
      lineEnd: { x: 0.55, y: 0.65 },
      width: 0.09,
      polygon: [],
      weightMap: { type: 'radial_gradient', center: { x: 0.5, y: 0.5 }, radius: 0.75 },
    },
    {
      id: 'mouth_natural_refine',
      enabled: true,
      type: 'radial_warp',
      target: 'mouth',
      strength: 0.02,
      radius: 1.1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1.05, y: 0.95 },
      direction: { x: 0, y: 0 },
      lineStart: { x: 0.36, y: 0.62 },
      lineEnd: { x: 0.64, y: 0.62 },
      width: 0.08,
      polygon: [],
      weightMap: { type: 'radial_gradient', center: { x: 0.5, y: 0.56 }, radius: 0.72 },
    },
    {
      id: 'left_jaw_natural_slim',
      enabled: true,
      type: 'line_warp',
      target: 'left_jaw',
      strength: 0.04,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: 0.02, y: 0 },
      lineStart: { x: 0.25, y: 0.47 },
      lineEnd: { x: 0.46, y: 0.73 },
      width: 0.1,
      polygon: [],
      binding: { type: 'landmark_line', start: 'left_cheek', end: 'chin' },
    },
    {
      id: 'right_jaw_natural_slim',
      enabled: true,
      type: 'line_warp',
      target: 'right_jaw',
      strength: 0.04,
      radius: 1,
      falloff: { type: 'smoothstep' },
      axis: { x: 1, y: 1 },
      direction: { x: -0.02, y: 0 },
      lineStart: { x: 0.75, y: 0.47 },
      lineEnd: { x: 0.54, y: 0.73 },
      width: 0.1,
      polygon: [],
      binding: { type: 'landmark_line', start: 'right_cheek', end: 'chin' },
    },
  ],
};
